DISPLAYNAME	:= Flappy Bird

INCLUDES	:=
LIBDIRS		:=

include ../common/project

CFLAGS		:=	$(GCFLAGS)
CXXFLAGS	:=	$(GCXXFLAGS)
LDFLAGS		:=	$(GLDFLAGS)

LIBS		:=	$(GLIBS)

include ../common/prizm_rules
